# Generated by Django 2.2.6 on 2020-03-10 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cerated_at',
            new_name='created_at',
        ),
    ]
